type AutoGenerated struct {
	Markets []struct {
		Quote struct {
			Nzd struct {
				Price     float64 `json:"price"`
				Volume24H float64 `json:"volume_24h"`
			} `json:"NZD"`
			Gbp struct {
				Price     float64 `json:"price"`
				Volume24H float64 `json:"volume_24h"`
			} `json:"GBP"`
			Jpy struct {
				Price     float64 `json:"price"`
				Volume24H float64 `json:"volume_24h"`
			} `json:"JPY"`
			Aud struct {
				Price     float64 `json:"price"`
				Volume24H float64 `json:"volume_24h"`
			} `json:"AUD"`
			Usd struct {
				Price     float64 `json:"price"`
				Volume24H float64 `json:"volume_24h"`
			} `json:"USD"`
			Cad struct {
				Price     float64 `json:"price"`
				Volume24H float64 `json:"volume_24h"`
			} `json:"CAD"`
			Eur struct {
				Price     float64 `json:"price"`
				Volume24H float64 `json:"volume_24h"`
			} `json:"EUR"`
		} `json:"quote"`
		ExchangeID       string  `json:"exchange_id"`
		Symbol           string  `json:"symbol"`
		BaseAsset        string  `json:"base_asset"`
		QuoteAsset       string  `json:"quote_asset"`
		PriceUnconverted float64 `json:"price_unconverted"`
		Price            float64 `json:"price"`
		Change24H        float64 `json:"change_24h"`
		Spread           float64 `json:"spread"`
		Volume24H        float64 `json:"volume_24h"`
		Status           string  `json:"status"`
		CreatedAt        string  `json:"created_at"`
		UpdatedAt        string  `json:"updated_at"`
	} `json:"markets"`
	Next string `json:"next"`
}