type AutoGenerated struct {
	Markets []Markets `json:"markets"`
	Next    string    `json:"next"`
}
type Nzd struct {
	Price     float64 `json:"price"`
	Volume24H float64 `json:"volume_24h"`
}
type Gbp struct {
	Price     float64 `json:"price"`
	Volume24H float64 `json:"volume_24h"`
}
type Jpy struct {
	Price     float64 `json:"price"`
	Volume24H float64 `json:"volume_24h"`
}
type Aud struct {
	Price     float64 `json:"price"`
	Volume24H float64 `json:"volume_24h"`
}
type Usd struct {
	Price     float64 `json:"price"`
	Volume24H float64 `json:"volume_24h"`
}
type Cad struct {
	Price     float64 `json:"price"`
	Volume24H float64 `json:"volume_24h"`
}
type Eur struct {
	Price     float64 `json:"price"`
	Volume24H float64 `json:"volume_24h"`
}
type Quote struct {
	Nzd Nzd `json:"NZD"`
	Gbp Gbp `json:"GBP"`
	Jpy Jpy `json:"JPY"`
	Aud Aud `json:"AUD"`
	Usd Usd `json:"USD"`
	Cad Cad `json:"CAD"`
	Eur Eur `json:"EUR"`
}
type Markets struct {
	Quote            Quote   `json:"quote"`
	ExchangeID       string  `json:"exchange_id"`
	Symbol           string  `json:"symbol"`
	BaseAsset        string  `json:"base_asset"`
	QuoteAsset       string  `json:"quote_asset"`
	PriceUnconverted float64 `json:"price_unconverted"`
	Price            float64 `json:"price"`
	Change24H        float64 `json:"change_24h"`
	Spread           float64 `json:"spread"`
	Volume24H        float64 `json:"volume_24h"`
	Status           string  `json:"status"`
	CreatedAt        string  `json:"created_at"`
	UpdatedAt        string  `json:"updated_at"`
}